Aarya Motiwala 
*   PRN-1132200331
*   ROLL no -8









**EXERCISE ▶**



---



**hiring.csv**
This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these
3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide
salaries for future candidates. Using this predict salaries for following candidates,
2 yr experience, 9 test score, 6 interview score
12 yr experience, 10 test score, 10 interview score

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ML LAB2/hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
df['test_score(out of 10)'].median()


8.0

In [ ]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].median())

In [ ]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
df.experience.mode()

0    eleven
1      five
2     seven
3       ten
4     three
5       two
dtype: object

In [ ]:
df.replace(to_replace='eleven',value=11,inplace=True)
df.replace(to_replace='five',value=5,inplace=True)
df.replace(to_replace='seven',value=7,inplace=True)
df.replace(to_replace='ten',value=10,inplace=True)
df.replace(to_replace='three',value=3,inplace=True)
df.replace(to_replace='two',value=2,inplace=True)

In [ ]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [ ]:
df.experience.median()

6.0

In [ ]:
df['experience'] = df['experience'].fillna(df.experience.median())

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('salary($)',axis='columns'),df['salary($)'])

LinearRegression()

In [ ]:
reg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [ ]:
reg.intercept_

11869.91869918695

In [ ]:
reg.predict([[2, 9, 6]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([47056.91056911])

In [ ]:
reg.predict([[12, 10, 10]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([88227.64227642])